
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 03 02:59:08 CST 2021
//----------------------------------------------------

package Jlex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 24;
  public static final int MENOS = 21;
  public static final int AGRUPACION = 15;
  public static final int AND = 6;
  public static final int MENOR = 25;
  public static final int MULTIPLICACION = 22;
  public static final int NE = 10;
  public static final int IGUAL = 29;
  public static final int MENORIGUAL = 27;
  public static final int OR = 7;
  public static final int DECIMAL = 33;
  public static final int IN = 11;
  public static final int DIVISION = 23;
  public static final int NOT = 8;
  public static final int PARIZQ = 2;
  public static final int ERROR = 17;
  public static final int PARDER = 3;
  public static final int POT = 18;
  public static final int ID = 31;
  public static final int NUM = 32;
  public static final int MAYOR = 26;
  public static final int EOF = 0;
  public static final int CORCIZQ = 5;
  public static final int MAYORIGUAL = 28;
  public static final int PI = 13;
  public static final int CORCDER = 4;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int PD = 30;
  public static final int COMENTARIO = 16;
  public static final int ASIG = 14;
  public static final int MAS = 20;
  public static final int DIF = 19;
  public static final int NI = 12;
}

