
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 03 03:36:23 CST 2021
//----------------------------------------------------

package Codigo_3_direcciones;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 8;
  public static final int POT = 37;
  public static final int PI = 50;
  public static final int EXPR = 18;
  public static final int PD = 49;
  public static final int PC = 2;
  public static final int CONTINUE = 27;
  public static final int PORCENTAJE = 43;
  public static final int INCR = 30;
  public static final int FOR = 29;
  public static final int MENORIGUAL = 46;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int IGUAL = 48;
  public static final int CORCIZQ = 36;
  public static final int ELSEIF = 23;
  public static final int AGRUPACION = 19;
  public static final int IN = 14;
  public static final int OR = 10;
  public static final int NUM = 52;
  public static final int IF = 20;
  public static final int ID = 51;
  public static final int MAYORIGUAL = 47;
  public static final int DECIMAL = 53;
  public static final int EOF = 0;
  public static final int PARIZQ = 33;
  public static final int RETURN = 32;
  public static final int error = 1;
  public static final int MENOS = 40;
  public static final int DIF = 38;
  public static final int COMENTARIO = 5;
  public static final int MENOR = 44;
  public static final int BREAK = 28;
  public static final int EQ = 12;
  public static final int IDE = 4;
  public static final int SWITCH = 24;
  public static final int MAYOR = 45;
  public static final int PUTS = 17;
  public static final int ELSE = 22;
  public static final int CORCDER = 35;
  public static final int WHILE = 26;
  public static final int NI = 15;
  public static final int DEFAULT = 25;
  public static final int THEN = 21;
  public static final int NE = 13;
  public static final int PROC = 31;
  public static final int PARDER = 34;
  public static final int DIVISION = 42;
  public static final int LLAVEC = 7;
  public static final int LLAVEA = 6;
  public static final int DP = 3;
  public static final int MULTIPLICACION = 41;
  public static final int SET = 16;
  public static final int MAS = 39;
}

