
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 01 02:08:23 CST 2021
//----------------------------------------------------

package Analizador;

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Thu Jun 03 02:08:23 CST 2021
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\025\003\000\002\027" +
    "\004\000\002\027\003\000\002\030\003\000\002\026\003" +
    "\000\002\026\003\000\002\026\003\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\017" +
    "\004\000\002\017\003\000\002\017\003\000\002\007\005" +
    "\000\002\014\005\000\002\014\004\000\002\014\006\000" +
    "\002\014\010\000\002\011\005\000\002\022\005\000\002" +
    "\022\005\000\002\022\005\000\002\022\005\000\002\022" +
    "\005\000\002\023\004\000\002\023\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\024\003\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\020\005\000\002\005" +
    "\011\000\002\005\015\000\002\004\013\000\002\015\006" +
    "\000\002\016\003\000\002\016\004\000\002\006\011\000" +
    "\002\010\020\000\002\012\014\000\002\021\003\000\002" +
    "\021\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\024\015\004\016\025\043\017\044\023\047" +
    "\013\053\012\055\006\060\026\062\022\001\002\000\032" +
    "\002\ufffb\015\ufffb\016\ufffb\020\ufffb\043\ufffb\044\ufffb\047" +
    "\ufffb\053\ufffb\055\ufffb\060\ufffb\062\ufffb\063\ufffb\001\002" +
    "\000\032\002\ufffe\015\004\016\025\020\ufffe\043\017\044" +
    "\023\047\013\053\012\055\006\060\026\062\022\063\ufffe" +
    "\001\002\000\004\017\166\001\002\000\032\002\ufff8\015" +
    "\ufff8\016\ufff8\020\ufff8\043\ufff8\044\ufff8\047\ufff8\053\ufff8" +
    "\055\ufff8\060\ufff8\062\ufff8\063\ufff8\001\002\000\032\002" +
    "\ufffa\015\ufffa\016\ufffa\020\ufffa\043\ufffa\044\ufffa\047\ufffa" +
    "\053\ufffa\055\ufffa\060\ufffa\062\ufffa\063\ufffa\001\002\000" +
    "\004\002\165\001\002\000\004\014\147\001\002\000\004" +
    "\017\135\001\002\000\032\002\ufff3\015\ufff3\016\ufff3\020" +
    "\ufff3\043\ufff3\044\ufff3\047\ufff3\053\ufff3\055\ufff3\060\ufff3" +
    "\062\ufff3\063\ufff3\001\002\000\032\002\ufff5\015\ufff5\016" +
    "\ufff5\020\ufff5\043\ufff5\044\ufff5\047\ufff5\053\ufff5\055\ufff5" +
    "\060\ufff5\062\ufff5\063\ufff5\001\002\000\032\002\ufff6\015" +
    "\ufff6\016\ufff6\020\ufff6\043\ufff6\044\ufff6\047\ufff6\053\ufff6" +
    "\055\ufff6\060\ufff6\062\ufff6\063\ufff6\001\002\000\004\014" +
    "\114\001\002\000\032\002\ufff4\015\ufff4\016\ufff4\020\ufff4" +
    "\043\ufff4\044\ufff4\047\ufff4\053\ufff4\055\ufff4\060\ufff4\062" +
    "\ufff4\063\ufff4\001\002\000\004\002\000\001\002\000\004" +
    "\014\101\001\002\000\010\015\075\017\074\046\073\001" +
    "\002\000\032\002\ufff9\015\ufff9\016\ufff9\020\ufff9\043\ufff9" +
    "\044\ufff9\047\ufff9\053\ufff9\055\ufff9\060\ufff9\062\ufff9\063" +
    "\ufff9\001\002\000\032\002\ufffc\015\ufffc\016\ufffc\020\ufffc" +
    "\043\ufffc\044\ufffc\047\ufffc\053\ufffc\055\ufffc\060\ufffc\062" +
    "\ufffc\063\ufffc\001\002\000\004\017\030\001\002\000\032" +
    "\002\ufff7\015\ufff7\016\ufff7\020\ufff7\043\ufff7\044\ufff7\047" +
    "\ufff7\053\ufff7\055\ufff7\060\ufff7\062\ufff7\063\ufff7\001\002" +
    "\000\004\043\032\001\002\000\004\020\041\001\002\000" +
    "\004\014\033\001\002\000\010\012\035\014\034\015\037" +
    "\001\002\000\032\002\ufff0\015\ufff0\016\ufff0\020\ufff0\043" +
    "\ufff0\044\ufff0\047\ufff0\053\ufff0\055\ufff0\060\ufff0\062\ufff0" +
    "\063\ufff0\001\002\000\032\002\ufff1\015\ufff1\016\ufff1\020" +
    "\ufff1\043\ufff1\044\ufff1\047\ufff1\053\ufff1\055\ufff1\060\ufff1" +
    "\062\ufff1\063\ufff1\001\002\000\032\002\uffef\015\uffef\016" +
    "\uffef\020\uffef\043\uffef\044\uffef\047\uffef\053\uffef\055\uffef" +
    "\060\uffef\062\uffef\063\uffef\001\002\000\004\014\040\001" +
    "\002\000\032\002\ufff2\015\ufff2\016\ufff2\020\ufff2\043\ufff2" +
    "\044\ufff2\047\ufff2\053\ufff2\055\ufff2\060\ufff2\062\ufff2\063" +
    "\ufff2\001\002\000\004\017\042\001\002\000\006\012\043" +
    "\015\046\001\002\000\042\006\uffe3\020\uffe3\021\uffe3\022" +
    "\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3" +
    "\031\uffe3\032\uffe3\037\uffe3\040\uffe3\041\uffe3\042\uffe3\001" +
    "\002\000\024\025\061\026\065\027\060\030\064\031\067" +
    "\037\063\040\071\041\062\042\066\001\002\000\004\020" +
    "\050\001\002\000\004\014\047\001\002\000\042\006\uffe4" +
    "\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026" +
    "\uffe4\027\uffe4\030\uffe4\031\uffe4\032\uffe4\037\uffe4\040\uffe4" +
    "\041\uffe4\042\uffe4\001\002\000\004\017\051\001\002\000" +
    "\004\061\052\001\002\000\004\014\053\001\002\000\004" +
    "\020\054\001\002\000\004\017\055\001\002\000\024\015" +
    "\004\016\025\043\017\044\023\047\013\053\012\055\006" +
    "\060\026\062\022\001\002\000\004\020\057\001\002\000" +
    "\032\002\uffd1\015\uffd1\016\uffd1\020\uffd1\043\uffd1\044\uffd1" +
    "\047\uffd1\053\uffd1\055\uffd1\060\uffd1\062\uffd1\063\uffd1\001" +
    "\002\000\006\012\uffde\015\uffde\001\002\000\006\012\uffe0" +
    "\015\uffe0\001\002\000\006\012\uffdb\015\uffdb\001\002\000" +
    "\006\012\uffdd\015\uffdd\001\002\000\006\012\uffdf\015\uffdf" +
    "\001\002\000\006\012\uffe1\015\uffe1\001\002\000\006\012" +
    "\uffda\015\uffda\001\002\000\006\012\uffe2\015\uffe2\001\002" +
    "\000\006\012\043\015\046\001\002\000\006\012\uffdc\015" +
    "\uffdc\001\002\000\004\020\uffd9\001\002\000\032\002\uffed" +
    "\015\uffed\016\uffed\020\uffed\043\uffed\044\uffed\047\uffed\053" +
    "\uffed\055\uffed\060\uffed\062\uffed\063\uffed\001\002\000\024" +
    "\015\004\016\025\043\017\044\023\047\013\053\012\055" +
    "\006\060\026\062\022\001\002\000\004\014\076\001\002" +
    "\000\032\002\uffea\015\uffea\016\uffea\020\uffea\043\uffea\044" +
    "\uffea\047\uffea\053\uffea\055\uffea\060\uffea\062\uffea\063\uffea" +
    "\001\002\000\004\020\100\001\002\000\032\002\uffec\015" +
    "\uffec\016\uffec\020\uffec\043\uffec\044\uffec\047\uffec\053\uffec" +
    "\055\uffec\060\uffec\062\uffec\063\uffec\001\002\000\004\017" +
    "\102\001\002\000\004\014\103\001\002\000\006\014\103" +
    "\020\uffcf\001\002\000\004\020\105\001\002\000\004\017" +
    "\106\001\002\000\024\015\004\016\025\043\017\044\023" +
    "\047\013\053\012\055\006\060\026\062\022\001\002\000" +
    "\004\063\110\001\002\000\010\012\035\014\034\015\037" +
    "\001\002\000\004\020\112\001\002\000\032\002\uffd0\015" +
    "\uffd0\016\uffd0\020\uffd0\043\uffd0\044\uffd0\047\uffd0\053\uffd0" +
    "\055\uffd0\060\uffd0\062\uffd0\063\uffd0\001\002\000\004\020" +
    "\uffce\001\002\000\014\007\116\012\035\014\034\015\037" +
    "\046\115\001\002\000\032\002\uffee\015\uffee\016\uffee\020" +
    "\uffee\043\uffee\044\uffee\047\uffee\053\uffee\055\uffee\060\uffee" +
    "\062\uffee\063\uffee\001\002\000\004\045\117\001\002\000" +
    "\006\012\043\015\046\001\002\000\004\006\134\001\002" +
    "\000\014\021\123\022\125\023\122\024\126\032\124\001" +
    "\002\000\006\012\043\015\046\001\002\000\006\012\043" +
    "\015\046\001\002\000\006\012\043\015\046\001\002\000" +
    "\006\012\043\015\046\001\002\000\006\012\043\015\046" +
    "\001\002\000\004\006\uffe6\001\002\000\004\006\uffe8\001" +
    "\002\000\004\006\uffe5\001\002\000\004\006\uffe9\001\002" +
    "\000\004\006\uffe7\001\002\000\032\002\uffeb\015\uffeb\016" +
    "\uffeb\020\uffeb\043\uffeb\044\uffeb\047\uffeb\053\uffeb\055\uffeb" +
    "\060\uffeb\062\uffeb\063\uffeb\001\002\000\006\012\043\015" +
    "\046\001\002\000\004\020\137\001\002\000\004\017\140" +
    "\001\002\000\024\015\004\016\025\043\017\044\023\047" +
    "\013\053\012\055\006\060\026\062\022\001\002\000\004" +
    "\020\142\001\002\000\034\002\uffd8\015\uffd8\016\uffd8\020" +
    "\uffd8\043\uffd8\044\uffd8\047\uffd8\051\143\053\uffd8\055\uffd8" +
    "\060\uffd8\062\uffd8\063\uffd8\001\002\000\004\017\144\001" +
    "\002\000\024\015\004\016\025\043\017\044\023\047\013" +
    "\053\012\055\006\060\026\062\022\001\002\000\004\020" +
    "\146\001\002\000\032\002\uffd7\015\uffd7\016\uffd7\020\uffd7" +
    "\043\uffd7\044\uffd7\047\uffd7\053\uffd7\055\uffd7\060\uffd7\062" +
    "\uffd7\063\uffd7\001\002\000\004\017\150\001\002\000\004" +
    "\046\151\001\002\000\004\017\162\001\002\000\006\046" +
    "\151\054\uffd4\001\002\000\004\054\154\001\002\000\004" +
    "\017\155\001\002\000\024\015\004\016\025\043\017\044" +
    "\023\047\013\053\012\055\006\060\026\062\022\001\002" +
    "\000\004\020\157\001\002\000\004\020\160\001\002\000" +
    "\032\002\uffd6\015\uffd6\016\uffd6\020\uffd6\043\uffd6\044\uffd6" +
    "\047\uffd6\053\uffd6\055\uffd6\060\uffd6\062\uffd6\063\uffd6\001" +
    "\002\000\004\054\uffd3\001\002\000\024\015\004\016\025" +
    "\043\017\044\023\047\013\053\012\055\006\060\026\062" +
    "\022\001\002\000\004\020\164\001\002\000\006\046\uffd5" +
    "\054\uffd5\001\002\000\004\002\001\001\002\000\006\012" +
    "\043\015\046\001\002\000\004\020\170\001\002\000\004" +
    "\017\171\001\002\000\024\015\004\016\025\043\017\044" +
    "\023\047\013\053\012\055\006\060\026\062\022\001\002" +
    "\000\004\020\173\001\002\000\032\002\uffd2\015\uffd2\016" +
    "\uffd2\020\uffd2\043\uffd2\044\uffd2\047\uffd2\053\uffd2\055\uffd2" +
    "\060\uffd2\062\uffd2\063\uffd2\001\002\000\010\002\uffff\020" +
    "\uffff\063\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\172\000\030\004\015\005\026\006\014\007\007\010" +
    "\017\011\023\012\013\014\006\025\010\026\004\027\020" +
    "\001\001\000\002\001\001\000\026\004\015\005\026\006" +
    "\014\007\007\010\017\011\023\012\013\014\006\026\004" +
    "\027\173\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\030\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\017\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\020\044\023\043\001\001\000\002" +
    "\001\001\000\004\024\067\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\004\015\005\026\006\014\007\007\010\017" +
    "\011\023\012\013\014\006\026\004\027\055\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\023\071\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\004\015\005\026\006\014" +
    "\007\007\010\017\011\023\012\013\014\006\026\004\027" +
    "\076\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\021" +
    "\103\001\001\000\004\021\112\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\004\015\005\026\006\014\007" +
    "\007\010\017\011\023\012\013\014\006\026\004\027\106" +
    "\001\001\000\002\001\001\000\004\017\110\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\017\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\022\117\023\120\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\023\132\001\001\000\004\023\131\001" +
    "\001\000\004\023\130\001\001\000\004\023\127\001\001" +
    "\000\004\023\126\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\020\135\023\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\026\004\015\005\026" +
    "\006\014\007\007\010\017\011\023\012\013\014\006\026" +
    "\004\027\140\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\004\015\005\026\006\014\007" +
    "\007\010\017\011\023\012\013\014\006\026\004\027\144" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\015\151\016\152\001\001\000\002\001\001" +
    "\000\006\015\151\016\160\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\004\015\005\026\006\014\007\007" +
    "\010\017\011\023\012\013\014\006\026\004\027\155\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\004\015\005\026\006\014\007" +
    "\007\010\017\011\023\012\013\014\006\026\004\027\162" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\020\166\023\043\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\004\015\005\026\006\014\007" +
    "\007\010\017\011\023\012\013\014\006\026\004\027\171" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        public static void main( String args[]) throws Exception{
		new parser(new Yylex(System.in)).parse();
	}
    /**
     * Método al que se llama automáticamente ante algún error sintactico.
     **/ 
    public void syntax_error(Symbol s){ 
        System.out.println("Error Sintáctico en la Línea " + (s.left) +
        " Columna "+s.right+ ". No se esperaba este componente: " +s.value+"."); 
    } 

    /**
     * Método al que se llama automáticamente ante algún error sintáctico 
     * en el que ya no es posible una recuperación de errores.
     **/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error síntactico irrecuperable en la Línea " + 
        (s.left)+ " Columna "+s.right+". Componente " + s.value + 
        " no reconocido."); 
    }  

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // ARGUMENTOS ::= ID ARGUMENTOS 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(15/*ARGUMENTOS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ARGUMENTOS ::= ID 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*ARGUMENTOS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // PROC01 ::= PROC ID LLAVEA ARGUMENTOS LLAVEC LLAVEA expr_list RETURN VALOR LLAVEC 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(8/*PROC01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // FOR01 ::= FOR LLAVEA SET01 LLAVEC LLAVEA TEST LLAVEC LLAVEA INCR ID LLAVEC LLAVEA expr_list LLAVEC 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(6/*FOR01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // WHILE01 ::= WHILE LLAVEA TEST LLAVEC LLAVEA expr_list LLAVEC 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(4/*WHILE01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // CASE01 ::= CASE CASE01 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(12/*CASE01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // CASE01 ::= CASE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*CASE01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // CASE ::= AGRUPACION LLAVEA expr_list LLAVEC 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(11/*CASE*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // SWITCH01 ::= SWITCH ID LLAVEA CASE01 DEFAULT LLAVEA expr_list LLAVEC LLAVEC 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(2/*SWITCH01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // IF01 ::= IF LLAVEA TEST LLAVEC LLAVEA expr_list LLAVEC ELSE LLAVEA expr_list LLAVEC 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*IF01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // IF01 ::= IF LLAVEA TEST LLAVEC LLAVEA expr_list LLAVEC 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*IF01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // TEST ::= OPERAR SIMBRELACIONAL OPERAR 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(14/*TEST*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // SIMBRELACIONAL ::= NI 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // SIMBRELACIONAL ::= IN 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // SIMBRELACIONAL ::= NE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // SIMBRELACIONAL ::= EQ 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // SIMBRELACIONAL ::= MENORIGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // SIMBRELACIONAL ::= MAYORIGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // SIMBRELACIONAL ::= MENOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // SIMBRELACIONAL ::= MAYOR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // SIMBRELACIONAL ::= IGUAL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*SIMBRELACIONAL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OPERAR ::= NUM 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*OPERAR*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPERAR ::= IDE ID 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*OPERAR*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPERACIONES ::= OPERAR PORCENTAJE OPERAR 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(16/*OPERACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // OPERACIONES ::= OPERAR DIVISION OPERAR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*OPERACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // OPERACIONES ::= OPERAR MULTIPLICACION OPERAR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*OPERACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // OPERACIONES ::= OPERAR MENOS OPERAR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*OPERACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // OPERACIONES ::= OPERAR MAS OPERAR 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*OPERACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // PUTS01 ::= PUTS IDE ID 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(7/*PUTS01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // AGRUPACIONES ::= SET ID CORCIZQ EXPR OPERACIONES CORCDER 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(10/*AGRUPACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // AGRUPACIONES ::= PUTS LLAVEA expr_list LLAVEC 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*AGRUPACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // AGRUPACIONES ::= PUTS AGRUPACION 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*AGRUPACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // AGRUPACIONES ::= SET ID AGRUPACION 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*AGRUPACIONES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SET01 ::= SET ID VALOR 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(5/*SET01*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // VALOR ::= ID 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(13/*VALOR*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // VALOR ::= NUM 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*VALOR*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // VALOR ::= IDE ID 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*VALOR*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= PROC01 
            {
              Object RESULT = null;
		 System.out.println("SENTENCIA CORRECTA"); 
              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= FOR01 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= WHILE01 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= SWITCH01 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= IF01 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= AGRUPACIONES 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= PUTS01 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= SET01 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= IDE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= COMENTARIO 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(20/*expr*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr_part ::= expr 
            {
              Object RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 System.out.println(" = "+e+";"); 
              CUP$parser$result = new java_cup.runtime.Symbol(22/*expr_part*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr_list ::= expr 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*expr_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr_list ::= expr expr_list 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(21/*expr_list*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // ini ::= expr_list 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(19/*ini*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= ini EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

