
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 03 00:24:41 CST 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 27;
  public static final int SL = 9;
  public static final int EXPR = 37;
  public static final int CONTINUE = 46;
  public static final int PC = 6;
  public static final int PORCENTAJE = 26;
  public static final int INCR = 49;
  public static final int FOR = 48;
  public static final int NOT = 30;
  public static final int MENORIGUAL = 23;
  public static final int AND = 28;
  public static final int ELSEIF = 42;
  public static final int CORCIZQ = 5;
  public static final int IGUAL = 25;
  public static final int AGRUPACION = 38;
  public static final int IN = 33;
  public static final int OR = 29;
  public static final int NUM = 11;
  public static final int IF = 39;
  public static final int ID = 12;
  public static final int MAYORIGUAL = 24;
  public static final int EOF = 0;
  public static final int PARIZQ = 2;
  public static final int RETURN = 51;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int COMENTARIO = 14;
  public static final int MENOS = 18;
  public static final int MENOR = 21;
  public static final int BREAK = 47;
  public static final int EQ = 31;
  public static final int IDE = 13;
  public static final int SWITCH = 43;
  public static final int MAYOR = 22;
  public static final int ELSE = 41;
  public static final int PUTS = 36;
  public static final int PUNTO = 10;
  public static final int CORCDER = 4;
  public static final int WHILE = 45;
  public static final int NI = 34;
  public static final int DEFAULT = 44;
  public static final int THEN = 40;
  public static final int NE = 32;
  public static final int PROC = 50;
  public static final int PARDER = 3;
  public static final int DIVISION = 20;
  public static final int LLAVEC = 16;
  public static final int LLAVEA = 15;
  public static final int DP = 7;
  public static final int SET = 35;
  public static final int MULTIPLICACION = 19;
  public static final int MAS = 17;
}

