
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 01 02:08:23 CST 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 25;
  public static final int EXPR = 35;
  public static final int CONTINUE = 44;
  public static final int PC = 6;
  public static final int PORCENTAJE = 24;
  public static final int INCR = 47;
  public static final int FOR = 46;
  public static final int NOT = 28;
  public static final int MENORIGUAL = 21;
  public static final int AND = 26;
  public static final int ELSEIF = 40;
  public static final int CORCIZQ = 5;
  public static final int IGUAL = 23;
  public static final int AGRUPACION = 36;
  public static final int IN = 31;
  public static final int OR = 27;
  public static final int NUM = 8;
  public static final int IF = 37;
  public static final int ID = 10;
  public static final int MAYORIGUAL = 22;
  public static final int EOF = 0;
  public static final int PARIZQ = 2;
  public static final int DECIMAL = 9;
  public static final int RETURN = 49;
  public static final int error = 1;
  public static final int COMENTARIO = 12;
  public static final int MENOS = 16;
  public static final int MENOR = 19;
  public static final int BREAK = 45;
  public static final int EQ = 29;
  public static final int IDE = 11;
  public static final int SWITCH = 41;
  public static final int MAYOR = 20;
  public static final int ELSE = 39;
  public static final int PUTS = 34;
  public static final int CORCDER = 4;
  public static final int WHILE = 43;
  public static final int NI = 32;
  public static final int DEFAULT = 42;
  public static final int THEN = 38;
  public static final int NE = 30;
  public static final int PROC = 48;
  public static final int PARDER = 3;
  public static final int DIVISION = 18;
  public static final int LLAVEC = 14;
  public static final int LLAVEA = 13;
  public static final int DP = 7;
  public static final int SET = 33;
  public static final int MULTIPLICACION = 17;
  public static final int MAS = 15;
}

